Repository bookbookbook-fe/core-javascript, pull requests merged in 2025-01, with the labels that each got.

#13 4주차 콜백 지옥 - 전형호
  hyeongho/chapter4_콜백 함수.md
Labels: 4주차

#12 [4주차] 콜백 함수 - sooyoung
  sooyoung/chapter4_콜백함수.md
Labels: 4주차

#15 [4주차] 콜백 함수 - seyeong
  seyeong/chapter4_콜백함수.md
Labels: 4주차

#18 [5주차] 클로저 - seyeong
  seyeong/chapter5_클로저.md
Labels: 5주차

#22 [7주차] 클래스 - sooyoung
  sooyoung/chapter6_프로토타입.md
  sooyoung/chapter7_클래스.md
Labels: 7주차 완료 🎉

#19 [5주차] 클로저 - hyelin
  hyelin/chapter5_클로저.md
Labels: 5주차

#23 [6주차] 프로토타입 - seyeong
  seyeong/chapter6_프로토타입.md
  seyeong/image/프로토타입_create(null).png
  seyeong/image/프로토타입_다중_체이닝1.png
  seyeong/image/프로토타입_다중_체이닝2.png
  seyeong/image/프로토타입_도식.png
  seyeong/image/프로토타입_배열의_내부_구조.png
  seyeong/image/프로토타입_배열의_내부_도식.png
  seyeong/image/프로토타입_전체_프로토타입_구조.png
Labels: 6주차
